### ISSUE TITLE
Can't login with standalone SFTP server 

### ISSUE THREAD

**Issue by Sporesirius** [ccarney16/pterodactyl-docker#10]
Hello,
I'm trying to get the standalone SFTP server to run but unfortunately when I try to login I get the following error:

`1.5575967038541293e+09	warn	server/server.go:122	failed to accept an incoming connection	{"error": "[ssh: no auth passed yet, could not validate credentials]"}`

I have also gone by the following instructions: https://pterodactyl.io/daemon/standalone_sftp.html (Disabled the Daemon SFTP)

sftp docker-compose.yml:

>   sftp:
>     image: ccarney16/pterodactyl-sftp:v1.0.1
>     ports:
>     - 2022:2022
>     restart: always
>     volumes_from:
>     - daemon

**Comment by ccarney16** [comment]
I'll have this checked out, I have not tested the sftp daemon extensively. is the sftp daemon able to contact the panel?

**Comment by Sporesirius** [comment]
Sorry about the delay.
Yes, the funny thing is if I deactivate the internal sftp server the web sftp will still work without having activated the standalone sftp.

**Comment by ADRFranklin** [comment]
I can also confirm that I get the same issue, no matter what authentication attempts you make they all fail.

**Comment by brandonjjon** [comment]
I also have a similar issue:

> server/server.go:122	failed to accept an incoming connection	{"error": "ssh: disconnect, reason 11: cleanup"}

When logging in, it prompts for password but it never accepts that password.

The internal SFTP works fine.

Thanks

**Comment by NgLoader** [comment]
WARNING
Standalone SFTP support was introduced in Panel@v0.7.11 and Daemon@v0.6.8 and will not work with prior versions.

Thats the error.

**Comment by ccarney16** [comment]
SFTP Daemon image is no longer maintained
