### ISSUE TITLE
Table 'pterodactyl.jobs' doesn't exist

### ISSUE THREAD

**Issue by D3vJust** [ccarney16/pterodactyl-docker#11]
Hey,

if I start the docker, I get a lot of 

`[2019-05-18 14:21:24] production.ERROR: QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pterodactyl.jobs' doesn't exist (SQL: select * from `jobs` where `queue` = high and ((`reserved_at` is null and `available_at` <= 1558189284) or (`reserved_at` <= 1558189194)) order by `id` asc limit 1 for update) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2062): Illuminate\Database\Connection->select
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2050): Illuminate\Database\Query\Builder->runSelect
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2536): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2051): Illuminate\Database\Query\Builder->onceWithColumns
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\Database\Query\Builder->get
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(223): Illuminate\Database\Query\Builder->first
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(199): Illuminate\Queue\DatabaseQueue->getNextAvailableJob
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Illuminate\Queue\DatabaseQueue->Illuminate\Queue\{closure}
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(204): Illuminate\Database\Connection->transaction
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(247): Illuminate\Queue\DatabaseQueue->pop
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(107): Illuminate\Queue\Worker->getNextJob
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker
#15 (0): Illuminate\Queue\Console\WorkCommand->handle
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call
#21 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run
#23 /var/www/html/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run
#24 /var/www/html/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand
#25 /var/www/html/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run
#28 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle  `

Errors.
Can you help me maybe?

**Comment by ccarney16** [comment]
I would check first with Pterodactyl Support if its an error on their end, as that is related to MySQL.

**Comment by D3vJust** [comment]
> I would check first with Pterodactyl Project if its an error on their end, as that is related to MySQL. I havent noticed that error in regards to my own setups, and including my test system

Okay, reinstalled completely - working now.
But I'm not able to access the daemon.
I've added 
`"interfaces": {
        "v4": {
          "subnet": "172.19.199.1/24",
          "gateway": "172.19.199.1"
        }
      }`
to the core.json.

Can you help me?

**Comment by Syntax3rror404** [comment]
I have installed pterodactyl with the container images from ccarney16 two months ago. I have this table. Please do not use mysql in version 8 that is currently not supported. I use the latest version of the mariadb image and everything works fine :). You can try to add this table by hand or try to reinstall it.
