### ISSUE TITLE
Problems with letsencrypt-nginx-proxy

### ISSUE THREAD

**Issue by Tobiplayer3** [ccarney16/pterodactyl-docker#13]
I'm having problems with the installation of the panel while using https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion. 
If I set all the environment variables required for the proxy and enable SSL in the .env file, I'm unable to load the panel because of the error "ERR_TOO_MANY_REDIRECTS". Disabling SSL in .env will allow me to access the panel but every time any action is done (logging in or something similar) Firefox warns me about an insecure connection.
I have no idea why that's not working, maybe you know why that happens?

Additionally any server installation will not finish and end with the following error `An error occured while attempting to alert the panel of server install status. { code: 405,
      responseBody: '{\n    "errors": [\n        {\n            "code": "MethodNotAllowedHttpException",\n            "status": "405",\n            "detail": "An error was encountered while processing this request."\n        }\n    ]\n}' }
`
I'm not entirely sure if that's related to the first problem but probably it is.

**Comment by ccarney16** [comment]
It is recommended to use ssl in front of the proxy, not on the panel container. Also, might I suggest trying traefik out?

**Comment by Tobiplayer3** [comment]
Seems like I forgot to allow reversed-proxies in my .env file as described on this page: https://pterodactyl.io/panel/configuration.html#reverse-proxy-setup.
I've also changed my proxy to traefik and everythink works now as intended.
I'll close this issue here, thanks for the help.
