### ISSUE TITLE
Pool overlaps with other one on this address space

### ISSUE THREAD

**Issue by thierrybla** [ccarney16/pterodactyl-docker#17]
I am getting an error while setting up a node.

Error: https://pastebin.com/8SFnhLxc

My docker-compose.yml: https://gist.github.com/thierrybla/84b2085f89bced8a280a37f1640ae825

My core.json: https://gist.github.com/thierrybla/514307fa6acdbf15dff06f5655e8a16f

Please let me know what I am doing wrong.

Thanks in advance.

**Comment by AngryKiller** [comment]
How did you fixed it?

**Comment by AngryKiller** [comment]
nvm I solved it

**Comment by NgLoader** [comment]
Your adress is already in use

**Comment by Bjornskjald** [comment]
How did you solve it?

**Comment by AleksaDjordjic** [comment]
> nvm I solved it

Can we know what was the fix for you @AngryKiller?
I'm having the same problem, looking for solutions.

**Comment by magnus919** [comment]
Dying from anticipation here.

**Comment by Oddwerth** [comment]
Did anyone here found a solution ?

**Comment by AngryKiller** [comment]
> > nvm I solved it
> 
> Can we know what was the fix for you @AngryKiller? I'm having the same problem, looking for solutions.

I don't exactly remember how I solved it, I think I just played around with the container network settings.
