### ISSUE TITLE
Supporting Mobile App

### ISSUE THREAD

**Issue by NgLoader** [ccarney16/pterodactyl-docker#18]
Can you support the new mobile app on pterodactyl-panel

https://pterodactyl.cloud/home

commands:
composer config repositories.cloud composer https://packages.pterodactyl.cloud
composer require friendsofphp/php-cs-fixer 2.15.1 --dev
composer require pterodactyl/mobile-addon --update-no-dev --optimize-autoloader
php artisan migrate

Commit: https://github.com/ccarney16/pterodactyl-docker/pull/19

**Comment by ccarney16** [comment]
I currently do not have plans on adding anything extra to the base panel installation, however I might see about making an extra step to set stuff up like this.

**Comment by NgLoader** [comment]
Okay
