### ISSUE TITLE
Core.json issue

### ISSUE THREAD

**Issue by raymondhardy** [ccarney16/pterodactyl-docker#2]
service not starting this is the error i see in the docker-compose logs

daemon_1  | + ------------------------------------ +
daemon_1  | |  No config file located for Daemon!  |
daemon_1  | |  Please create a configuration file  |
daemon_1  | |  at config/core.json with the info   |
daemon_1  | |  provided by Pterodactyl Panel when  |
daemon_1  | |  you created this node.              |
daemon_1  | + ------------------------------------ +
daemon_1  | Trace: Cannot find module '/srv/daemon/config/core.json'
daemon_1  |     at Config.raw (/srv/daemon/src/helpers/config.js:50:25)
daemon_1  |     at new Config (/srv/daemon/src/helpers/config.js:34:38)
daemon_1  |     at Object.<anonymous> (/srv/daemon/src/helpers/logger.js:30:16)
daemon_1  |     at Module._compile (module.js:573:30)
daemon_1  |     at Object.Module._extensions..js (module.js:584:10)
daemon_1  |     at Module.load (module.js:507:32)
daemon_1  |     at tryModuleLoad (module.js:470:12)
daemon_1  |     at Function.Module._load (module.js:462:3)
daemon_1  |     at Module.require (module.js:517:17)
daemon_1  |     at require (internal/module.js:11:18)

**Comment by ccarney16** [comment]
Sorry for the very late delay, but the core.json file needs to be generated by the panel before hand, I recommend using `docker-compose up -d panel`.
