### ISSUE TITLE
Scheduler not working

### ISSUE THREAD

**Issue by Mapsred** [ccarney16/pterodactyl-docker#20]
Hi
I am running the version 0.7.14 of the pterodactyl panel
DISABLE_WORKERS is set to false

In the process the queue:work command is running

```
/var/www/html # ps aux | grep php
   16 root      0:03 php /var/www/html/artisan queue:work database --queue=high,standard,low --sleep=3 --tries=3 
   17 root      0:00 {php-fpm7} php-fpm: master process (/etc/php7/php-fpm.conf)
  554 root      0:00 grep php
```

The schedules are never triggered even when I run manually the command ``php /var/www/html/artisan schedule:run >> /dev/null 2>&1``

The only way to run a schedule is to manually trigger it with the Trigger Schedule button.

Any idea on how to resolve this ?

Thanks

**Comment by ccarney16** [comment]
hm, looks like cron is not running within the container. I would recommend trying to restart the container. I currently do not have a failsafe for the container itself to restart cron.

**Comment by Mapsred** [comment]
The cron seems to be running fine 
![image](https://user-images.githubusercontent.com/13522273/63108543-6eaf8e80-bf87-11e9-8582-811268a7c528.png)

But even if I run the following command manually (instead of as a cron) it does not trigger the schedules
``php /var/www/html/artisan schedule:run >> /dev/null 2>&1``

**Comment by NgLoader** [comment]
Your running this in the docker container or not?

**Comment by NgLoader** [comment]
Are your running the command in the docker container?

**Comment by Mapsred** [comment]
Yes, this command is in the panel container

**Comment by edpetremann** [comment]
Hi, we fixed this issue by increasing pm.max_children (9 by default) in manifest/panel/etc/php7/php-fpm.d. Looked on the /var/log/php7/error.log:
[09-Nov-2019 13:05:48] WARNING: [pool www] server reached max_children setting (9), consider raising it
```
[php-fpm-pool-settings]  
pm.max_children = 9 <--
```

**Comment by ccarney16** [comment]
I have noticed this issue for quite some time and was looking for a fix. I'll be sure to test this within the coming week and publish new images. In the meantime, I would recommend building the container or mounting a custom config file until then.

**Comment by triptronics** [comment]
Hey guys, any progress on this? I am having the exact same problem and I checked my php7 max_childeren setting as recommended by @edpetremann but it was already set to 20 by default. I don't have workers disabled. Much appreciated, thank you!

**Comment by edpetremann** [comment]
@triptronics try to change the schedule command:
From : php artisan schedule:run >> /dev/null 2>&1
To : php p:schedule:process >> /dev/null 2>&1

**Comment by triptronics** [comment]
> @triptronics try to change the schedule command:
> From : php artisan schedule:run >> /dev/null 2>&1
> To : php artisan p:schedule:process >> /dev/null 2>&1
> 
> If it works, edit this file with the new command : manifest/panel/etc/crontabs/nginx

Will try, thank you for the suggestion!

**Comment by triptronics** [comment]
> @triptronics try to change the schedule command:
> From : php artisan schedule:run >> /dev/null 2>&1
> To : php artisan p:schedule:process >> /dev/null 2>&1
> 
> If it works, edit this file with the new command : manifest/panel/etc/crontabs/nginx

Hi @edpetremann,

It seems like it does work when I run it manually. The problem here is that I don't think my cron is running at all. When I run crond start, there is no output but it also doesn't give any error. I can't view any logs either because there is only logs for nginx and php. How could I enable the service command so I can start the cron etc? I'm not entirely sure what image the panel is using. Thank you!

**Comment by edpetremann** [comment]
@triptronics This repo has a folder manifest that contains nginx file "https://github.com/ccarney16/pterodactyl-docker/tree/master/manifest/panel/etc/crontabs".

There is a symlink in the container so we added a volume with the folder that contains our crontab file. The main goal is to place a file which contains "php artisan p:schedule:process >> /dev/null 2>&1" into /var/spool/cron/crontabs. In this configuration, "/home/crontab_folder" contains this file.

```
volumes:
    - >local path to the crontab file, for example /home/crontab_folder<:/var/spool/cron/crontabs
```

**Comment by triptronics** [comment]
Hi @

> @triptronics This repo has a folder manifest that contains nginx file "https://github.com/ccarney16/pterodactyl-docker/tree/master/manifest/panel/etc/crontabs".
> 
> There is a symlink in the container so we added a volume with the folder that contains our crontab file. The main goal is to place a file which contains "`* * * * * php /var/www/html/artisan p:schedule:process >> /dev/null 2>&1`" into `/var/spool/cron/crontabs` :
> 
> _In the panel section of docker-compose.yml_
> 
> ```
>   volumes:
>   - local_path_that_contains_crontab_file:/var/spool/cron/crontabs
> 

YES! We have schedulers :) Thank you so much @edpetremann 

Initially, I attempted to edit the /etc/crontabs/nginx directly in the container but that didn't work. Creating a new file and adding it as a host mount did the trick, however. Do you happen to know why your command worked but the original one doesn't? This is good for documentation purposes as we are using your containers for our platform and we can't thank you enough. Much appreciated.

**Comment by Syntax3rror404** [comment]
I don't have this problem with the latest image version.

**Comment by Syntax3rror404** [comment]
You can clone the repo and change the file in the manifest files. Then run the build command in the bin folder to create your own container image with the right command.

**Comment by TheIronMinerLv** [comment]
Hi, I did the same stuff as mentioned in this issue (including PR), but my scheduler still isn't working... I've edited the files, do I need to rebuild image or something?

**Comment by Syntax3rror404** [comment]
You can mount the file with the manipulated settings to the right path from the container, or you pull this repo and change the value in the manifest and rebuild the container. If you mount the file to the container you dont need to rebuild it.

**Comment by Syntax3rror404** [comment]
If you go inside the container and edit the file via docker exec, the changes are gone with a restart and never loaded because the cron service need a restart.

**Comment by TheIronMinerLv** [comment]
Thanks for quick reply, I just set in docker-compose.yml it in a such way:
`    volumes:
    - ./data:/data
    - ./manifest/panel/etc/crontabs/nginx:/var/spool/cron/crontabs`

Not sure why it doesn't work.

**Comment by TheIronMinerLv** [comment]
*Edited, after setting that I restarted all ptero-related containers

**Comment by Syntax3rror404** [comment]
Ok... :D i have rebuild the image with the right command: mzapf/pterodactyl-panel:v0.7.17 you can pull this image its public. Its the newest panel version.

**Comment by Syntax3rror404** [comment]
Does it work now?

**Comment by TheIronMinerLv** [comment]
I'll try it today, thanks for help.
