### ISSUE TITLE
Unable to create any servers - invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by sephallen** [ccarney16/pterodactyl-docker#22]
I am unable to create any servers on my setup.
My volumes are default in the docker-compose.yaml.
I can create files from within the container at `/srv/daemon-data`, so it doesn't appear to be a permissions issue.

Here is the output from my log:

```
08:43:07.605Z WARN wings: Container was not found. Attempting to recreate it. (server=29159249-55d9-41cb-a03d-e762f5612d5c)
08:43:07.610Z INFO wings: Checking if we need to update image quay.io/parkervcp/pterodactyl-images:wine-source, if so it will happen now.
08:43:09.332Z INFO wings: Pulling image quay.io/parkervcp/pterodactyl-images:wine-source ... this could take a few minutes.
08:43:10.150Z FATAL wings: A fatal error was encountered while attempting to create a server.

Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist: /srv/daemon-data/29159249-55d9-41cb-a03d-e762f5612d5c

at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
at process._tickDomainCallback (internal/process/next_tick.js:219:9)
08:43:10.162Z INFO wings: Server deleted. (server=29159249-55d9-41cb-a03d-e762f5612d5c)
08:43:10.358Z INFO wings: Notified remote panel of server install status.
```

**Comment by ccarney16** [comment]
That is an issue with the pterodactyl daemon, not my containers in question. Feel free to file a bug report there.

**Comment by Official-Instructions** [comment]
Did you ever fix this @sephallen ?

**Comment by tobias231h** [comment]
I changed the host-location of the volumes to /opt/pterodactyl/... and had the same errors.
Resetting the locations to the original path (/srv/daemon/...) did the trick.

So you can't change these lines in the docker-compose.yml file:
    volumes:
    - /srv/daemon/config:/srv/daemon/config
    - /srv/daemon/packs:/srv/daemon/packs
    - /srv/daemon-data:/srv/daemon-data

**Comment by ccarney16** [comment]
You can change the location of `/srv/daemon-data`, but due to limitations in the daemon, it has to be mapped 1:1. All directories in `/srv/daemon` cannot be changed as of right now.
