### ISSUE TITLE
Page 404 after resetting passwords

### ISSUE THREAD

**Issue by Syntax3rror404** [ccarney16/pterodactyl-docker#24]
I have a 404 not found Page after klicking the password forgot button on the login screen. 
Missing files?

**Comment by ccarney16** [comment]
Is your container modified, I did not change anything within the panel save for the storage/cache directory. Can you provide a nginx error log that is within the storage directory, should be by the name of `access.error.log`.

**Comment by Syntax3rror404** [comment]
No, i don't change anything. In which volume can i find the log? And it isn't a 404 Error rather a 500 internal server error. I become the error also on  submitting a time job page.

**Comment by Syntax3rror404** [comment]
Here the file storage/logs/access.error.log from the Data Panel Volume. 

`2019/11/11 08:40:18 [error] 19#19: *19 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(142): I...PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/fr
2019/11/11 08:40:22 [error] 19#19: *21 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(142): I...PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/fr
2019/11/11 08:40:23 [error] 19#19: *23 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(142): I...PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/fr
2019/11/11 08:40:28 [error] 19#19: *25 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(142): I...PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/fr
2019/11/12 17:24:54 [error] 18#18: *190 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(142): I...PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/data/storage/f...', '<?php $__env->s...', 0)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/data/storage/f...', '<?php $__env->s...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/v...')
#4 /var/www/html/vendor/laravel/f
`

**Comment by ccarney16** [comment]
Edited your post for readability.

looks like a permission denied on the filesystem, please be sure that your permission for nginx/php is correctly set. I normally recommend resetting permissions within the container and using `chown` to nginx. I do plan on fixing this in future container updates by automatically resetting permissions on container restart.

**Comment by Syntax3rror404** [comment]
Hi thank you for answering :) 

I don't change your Image and the Permissions. I try your solution. If this solves this problem i can make a merge request if you want.

**Comment by Syntax3rror404** [comment]
Which path should I go through with chown?

**Comment by Syntax3rror404** [comment]
If i klick in the Webinterface under Database to a Database i become the same error.

**Comment by Syntax3rror404** [comment]
`chown -R nginx /data/` solve this problems :)
