### ISSUE TITLE
Error get Node Information

### ISSUE THREAD

**Issue by Syntax3rror404** [ccarney16/pterodactyl-docker#26]
When clicking on Management/Nodes. I get a (Latest:error) information.

Example:

Daemon Version | 0.6.12 (Latest: error)
-- | --
System Information | Linux(x64) 5.3.0-23-generic
Total CPU Cores | 12

I don't change anything inside the container or the volumes.

**Comment by ccarney16** [comment]
It looks like an issue in regards to the panel not getting info from github, this has not been modified in anyway from the vanilla panel installation. This could be the case of pterodactyl just not able to get info from a remote server.

**Comment by Syntax3rror404** [comment]
Thank you ccarney16, i close this issue.
