### ISSUE TITLE
Adding external worker/cron may have corrupted the mysql database

### ISSUE THREAD

**Issue by triptronics** [ccarney16/pterodactyl-docker#27]
Hello there, as a follow up from my comment on issue #20, I tried to use the information provided in the docker extra yml in the core.yml to add two separate containers for the worker and cron (I also added the SFTP container for SFTP support). I simply added the extra configuration for cron, worker, and sftp to the end of the core.yml file and then I changed the .env to disable_worker process true. Then I ran the following:

docker-compose up --force-recreate --build  

Eventually, the daemon container starts but I receive the following error:

daemon_1  | 
daemon_1  | > pteronode@0.6.12 start /srv/daemon
daemon_1  | > node src/index.js | node_modules/bunyan/bin/bunyan -o short
daemon_1  | 
daemon_1  | 18:50:37.931Z  INFO wings: + ------------------------------------ +
daemon_1  | 18:50:37.933Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    |
daemon_1  | 18:50:37.933Z  INFO wings: |        https://pterodactyl.io        |
daemon_1  | 18:50:37.933Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |
daemon_1  | 18:50:37.933Z  INFO wings: + ------------------------------------ +
daemon_1  | 18:50:37.933Z  INFO wings: Loading modules, this could take a few seconds.
daemon_1  | 18:50:38.426Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
daemon_1  | 18:50:38.532Z  INFO wings: Configuring user pterodactyl (id: 500) as the owner of all server files.
daemon_1  | 18:50:38.536Z  INFO wings: Configuring timezone file location...
daemon_1  | 18:50:38.536Z  INFO wings: Checking container networking environment...
daemon_1  | 18:50:38.614Z  INFO wings: Found network interface for daemon: pterodactyl_nw
daemon_1  | 18:50:38.614Z  INFO wings: Ensuring correct network interface for containers...
daemon_1  | 18:50:38.625Z  INFO wings: Networking gateway detected as 182.18.0.1 for interface: pterodactyl0.
daemon_1  | 18:50:38.627Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
panel_1   | 2019/11/22 18:50:38 [error] 16#16: *11 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class db.connection does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
panel_1   | Stack trace:
panel_1   | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('db.connection')
panel_1   | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('db.connection')
panel_1   | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('db.connection', Array)
panel_1   | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('db.connection', Array)
panel_1   | #4 /var/www/html/app/Exceptions/Handler.php(142): Illuminate\Foundation\Application->make('db.connection')
panel_1   | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Pterodactyl\Exceptions\Handle...PHP message: PHP Fatal error:  Uncaught ReflectionException: Class db.connection does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
panel_1   | Stack trace:
panel_1   | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('db.connection')
panel_1   | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('db.connection')
panel_1   | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('db.connection', Array)
panel_1   | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('db.connection', Array)
panel_1   | #4 /var/www/html/app/Exceptions/Handler.php(142): Illuminate\Foundation\Application->make('db.connection')
panel_1   | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExcept
panel_1   | src:"172.18.0.1" time:"22/Nov/2019:18:50:38 +0000" req:"GET /api/remote/eggs HTTP/1.1" status:"500" agent:"-" for:"-"
daemon_1  | 18:50:38.722Z FATAL wings: A fatal error caused the daemon to abort the startup.
daemon_1  |     Error: Error while attempting to fetch list of Eggs from the panel.
daemon_1  |         at Request [as _callback] (/srv/daemon/src/controllers/service.js:95:31)
daemon_1  |         at Request.self.callback (/srv/daemon/node_modules/request/request.js:185:22)
daemon_1  |         at emitTwo (events.js:126:13)
daemon_1  |         at Request.emit (events.js:214:7)
daemon_1  |         at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1157:10)
daemon_1  |         at emitOne (events.js:116:13)
daemon_1  |         at Request.emit (events.js:211:7)
daemon_1  |         at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1079:12)
daemon_1  |         at Object.onceWrapper (events.js:313:30)
daemon_1  |         at emitNone (events.js:111:20)
daemon_1  |     --
daemon_1  |     additional: {
daemon_1  |       "responseCode": 500,
daemon_1  |       "requestURL": "http://192.168.1.114/api/remote/eggs"

I try to go to the main panel home and it's throwing a 500 error, generic page (not thrown by Pterodactyl's fancy 500 error page).

I then removed the worker and cron from the core.yml and ran this command again:

docker-compose up --force-recreate --build  

But I keep getting the same error, even with the worker and cron now removed. Somehow these two containers might have corrupted the database because with them not even mentioned in the core yml file... there is that db problem that did not exist before.

To be sure, I deleted all directories related to the container on the host and tried again... same error even with a fresh install.

To further isolate, I started from scratch again and this time only added the SFTP container to the core yml. This time, nothing crashed. So there is something wrong with your images for the worker/cron.

You could probably further isolate to see if it's both causing the issue or one of the two.

Luckily this was just a test setup, but it would have been unfortunate to run this in production!

**Comment by ccarney16** [comment]
I don't think this is an issue with the container, I might suggest reproducing the test on a test server with the panel running outside of docker.

**Comment by Syntax3rror404** [comment]
I have more deamons running on different docker hosts and don't have this problem. Do you use the latest image version? Do you have a mysql 8 server? Mysql 8 isn't supported by pterodactyl.
