### ISSUE TITLE
Problems with server-docker IP and ports (all IPs binding together)

### ISSUE THREAD

**Issue by TheIronMinerLv** [ccarney16/pterodactyl-docker#32]
Hello,

Following the installation, I ran into some issues with setting up correct networking parameters in core.json.

I have 4 IPs, that I've added to my Debian 10 network interfaces. To configure `core.json`, I followed mostly [ptero docs](https://pterodactyl.io/daemon/configuration.html#custom-network-interfaces) where I found about additional networking parameters.

**Main problem - after starting daemon, no matter what IP and port I allocate to my node, I can connect to pterodactyl server with any of those 4 IPs.**

Here is what I tried, what worked and what didn't.
- By setting `docker.network.name` to `host`, daemon starts and I have that IP binding issue above;
- By setting just `docker.network.interfaces.v4.subnet` and `docker.network.interfaces.v4.gateway` daemon doesn't start;
- I tried many different combinations but maybe I don't clearly understand how pterodactyl needs to hook with my networking.

+ With `docker container ls` I found out that my started server "PORTS" section is empty.

**Could you please help me with setting this up correctly?**

**Comment by ccarney16** [comment]
I believe that's an issue with pterodactyl itself. I have never used the host networking stack when I have deployed my containers.

**Comment by TheIronMinerLv** [comment]
Then how would you set up? I couldn't get it working without "host", but maybe I did something wrong...

**Comment by ccarney16** [comment]
To sum it up, regenerate your daemon config and create the pterodactyl_nw manually. Pterodactyl has this odd tendency to not create it's network if "assigned" address range is not available (docker compose by default creates a network per project, taking the default internal allocation), but will not be picky if the network already exists.

**Comment by TheIronMinerLv** [comment]
I was able to resolve this myself with default pterodactyl network. Thanks for suggestion!
