### ISSUE TITLE
alpine:edge Panel

### ISSUE THREAD

**Issue by Official-Instructions** [ccarney16/pterodactyl-docker#36]
The [panel dockerfile](https://github.com/ccarney16/pterodactyl-docker/blob/master/manifest/panel/Dockerfile) uses alpine:edge as its base.

According to [this Alpine page,](https://wiki.alpinelinux.org/wiki/Edge)

> _Warning: "edge" is under constant development so be careful using it in production. It is possible that bugs in "edge" could cause data loss or could break your system._

> End users should not use "edge" as their main day-to-day workstation or as productive system. Because "edge" is a development branch, many changes are not heavily tested (or tested at all) and packages in "edge" can and sometimes do break without warning.

Should there be a change to a more stable branch of alpine?

**Comment by Official-Instructions** [comment]
The Dockerfile of the Panel source uses alpine:3.8

```
FROM alpine:3.8

WORKDIR /app

RUN apk add --no-cache --update ca-certificates certbot nginx dcron curl tini php7 php7-bcmath php7-common php7-dom p
hp7-fpm php7-gd php7-mbstring php7-openssl php7-zip php7-pdo php7-phar php7-json php7-pdo_mysql php7-session php7-cty
pe php7-tokenizer php7-zlib php7-simplexml php7-fileinfo supervisor \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . ./

RUN cp .env.example .env \
 && composer install --no-dev --optimize-autoloader \
 && rm .env \
 && chown -R nginx:nginx . && chmod -R 777 storage/* bootstrap/cache

RUN cp .dev/docker/default.conf /etc/nginx/conf.d/default.conf \
 && cp .dev/docker/www.conf /etc/php7/php-fpm.d/www.conf \
 && cat .dev/docker/supervisord.conf > /etc/supervisord.conf \
 && echo "* * * * * /usr/bin/php /app/artisan schedule:run >> /dev/null 2>&1" >> /var/spool/cron/crontabs/root \
 && sed -i s/ssl_session_cache/#ssl_session_cache/g /etc/nginx/nginx.conf \
 && mkdir -p /var/run/php /var/run/nginx

EXPOSE 80 443

ENTRYPOINT ["/bin/ash", ".dev/docker/entrypoint.sh"]

CMD [ "supervisord", "-n", "-c", "/etc/supervisord.conf" ]
```

**Comment by ccarney16** [comment]
I used alpine:edge mainly for an updated version of PHP that an older version of alpine did not have. It has since been updated. However I have no intentions on moving back to alpine:3.8 for the v0.7.x panel releases. This will change moving forward to v0.8 (Unless pterodactyl requires a newer version of PHP that a stable alpine build does not provide).
