### ISSUE TITLE
500 Error behind jwilder/nginx-proxy

### ISSUE THREAD

**Issue by ratatouyee** [ccarney16/pterodactyl-docker#39]
I'm trying to run the panel behind [jwilder/nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) and it's giving me a 500 error page: The 404 page seems to load properly at least.

> 500
> Whoops, something went wrong on our servers. 
> Go home

I was able to access the panel login page before setting up the proxy, but haven't logged in yet to setup the daemon.

##### .env
```##
# Pterodactyl Container Variables
#
# DO NOT OVERWRITE WITH PTERODACTYL ".env" CONFIGURATIONS!
# This configuration may look like it has pterodactyl
# variables, and it does, however this config also contains
# variables to initialize/setup the containers. If you are migrating
# or planning to use /data/pterodactyl.conf for all your variables,
# remove anything after "panel variables" stated.
##


# MySQL Settings, These can be deleted if you don't use the mysql service within docker-compose.yml
MYSQL_ROOT_PASSWORD=redacted
MYSQL_DATABASE=pterodactyl
MYSQL_USER=ptero
MYSQL_PASSWORD=redacted

##
# Container Variables
##

# was trying around with SSL=true, causes 502 Bad Gateway
# unsure which cert & key to pick
SSL=false
SSL_CERT="/srv/www/nginx-proxy/certs/ptero.domain.tld.fullchain.pem"
SSL_CERT_KEY="/srv/www/nginx-proxy/certs/ptero.domain.tld.key"

# Disable's runtime workers & cronjob (this is useful if you want to run these in another container)
DISABLE_WORKERS=false

##
# Panel Variables
# These variables can be used within pterodactyl.conf (.env when symlinked 
# into the docker webroot). These variables are also set via pterodactyl:env
# and pterodactyl:mail.
##
APP_URL=http://localhost/

TIMEZONE=UTC

CACHE_DRIVER=memcached

RECAPTCHA_ENABLED=false

TRUSTED_PROXIES=*

# Rely on an external source so we can put the panel container down when updates are needed
REDIS_HOST=cache
REDIS_PORT=6379

DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=pterodactyl
DB_USERNAME=ptero
DB_PASSWORD=redacted

MAIL_DRIVER=mail
MAIL_FROM=admin@localhost
MAIL_FROM_NAME="Pterodactyl Panel"

DOCKER_ROOT=/var/lib/docker
DOCKER_SOCKET=/var/run/docker.sock
```
##### docker-compose.yml
```
##
# Pterodactyl Daemon
# If you don't plan on running the daemon on the same machine, 
# you may comment/delete the section below.
##
  daemon:
    depends_on:
    - panel
    image: ccarney16/pterodactyl-daemon:latest
    container_name: ptero-daemon
    expose:
    -  8080
    environment:
      VIRTUAL_HOST: node1.ptero.domain.tld
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ptero.domain.tld
      LETSENCRYPT_EMAIL: redacted
    networks:
      - proxy
    privileged: true
    restart: always
    volumes:
    - ./data/srv/daemon/config:/srv/daemon/config
    - ./data/srv/daemon/packs:/srv/daemon/packs
    - ./data/srv/daemon-data:/srv/daemon-data

    - ./data/tmp/pterodactyl:/tmp/pterodactyl

    - /etc/localtime:/etc/localtime

    # Docker socket and directory, needed to communicate to docker
    # NOTE: If you are using docker in a different directory, please change below to reflect that!
    - ${DOCKER_ROOT:-/var/lib/docker}:${DOCKER_ROOT:-/var/lib/docker}
    - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
networks:
  proxy:
    external:
      name: proxy
```
##### docker-compose logs panel
```
panel_1   | src:"172.18.0.3" time:"08/Mar/2020:08:49:00 +0000" req:"GET / HTTP/1.1" status:"500" agent:"[my user agent]" for:"[my ip]"
panel_1   | src:"172.18.0.3" time:"08/Mar/2020:08:49:01 +0000" req:"GET /svg/500.svg HTTP/1.1" status:"404" agent:"[my user agent]" for:"[my ip]"
```
I made sure to add the daemon to the proxy's networkm as proposed by ccarney16/pterodactyl-docker#38, to no avail.

**Comment by ccarney16** [comment]
Can the panel be contacted fine without going through nginx-proxy? Ive never used that image for my setups and relied more on HAProxy in the past and Traefik now.

**Comment by ratatouyee** [comment]
I had access to the login page before setting up the proxy, yes. Didn't try logging in because I wanted to setup HTTPS beforehand. I'll have to try disabling the proxy and see if it's still the case.

**Comment by ccarney16** [comment]
I would also recommend seeing if adding in `0.0.0.0/0` rather than `*` in TRUSTED_PROXIES as I would recommend doing CIDR notation.

**Comment by ratatouyee** [comment]
I can confirm the panel is working without a proxy. `TRUSTED_PROXIES=0.0.0.0/0` didn't change anything.

**Comment by ratatouyee** [comment]
I was also able to login, so I'm assuming it's an issue with nginx-proxy, either user error or a config not generating properly.

**Comment by ccarney16** [comment]
I have not tested `nginx-proxy` during testing with my container, I can only confirm that haproxy and traefik (both in docker containers) have worked. would you be able to get the nginx configuration generated for the panel?

**Comment by ratatouyee** [comment]
I'm not really familiar with haproxy or traefik and I wanted to use nginx-proxy  because I was planning to host multiple services on the server. I'm considering my options, might just do it the normal way with the official nginx image or figure out haproxy or traefik.

**Comment by ccarney16** [comment]
I am biased, but I have worked with nginx-proxy before and was not a big fan of it. HAProxy is nice for its stats usage but for docker it can be a chore to work on the config. Traefik is the only contender that works with docker out of the box along with other options. I do have a project on github that uses the older traefik 1.x series, which you can check out here: https://github.com/ccarney16/docker.webproxy

**Comment by ratatouyee** [comment]
I managed to fix the issue by just deleting nginx-proxy and reinstalling it following the instructions and docker-compose examples linked on the Github repo instead of some outdated blogpost.

**Comment by sevospl** [comment]
> I managed to fix the issue by just deleting nginx-proxy and reinstalling it following the instructions and docker-compose examples linked on the Github repo instead of some outdated blogpost.

Would you like to show your exact config, env, docker-compose file to get nginx-proxy running up together with pterodactyl?
