### ISSUE TITLE
Update deamon to v0.6.13

### ISSUE THREAD

**Issue by Syntax3rror404** [ccarney16/pterodactyl-docker#44]
Hi,

can you please update the deamon to the newes version? 

[Link to the new Version](https://github.com/pterodactyl/daemon/releases/tag/v0.6.13)

Thanks :)

**Comment by Official-Instructions** [comment]
I have updated my PR #42 to inculde the daemon switch, I am not sure why it was changed. The daemon was involved in the security vulnerability and updates seamlessly from my testing.

**Comment by Syntax3rror404** [comment]
I only changed the vars to v0.6.13 and build the container myself and it worked perfectly.
