### ISSUE TITLE
Pterodactyl and Traefik

### ISSUE THREAD

**Issue by Kourgiantakis** [ccarney16/pterodactyl-docker#46]
Hey,

i couldn't get ssl to run, i dont know why. You mentioned traefik somewhere else. Would you be willing to share how you did it? I've never worked with traefik before and would like to see your config for the use with ptero.

**Comment by Syntax3rror404** [comment]
The panel container use nginx not traefik. If you have problems with SSL you can use your own reverse proxy behind the containers with letsencrypt or what you want. For this setup you must configure in the env SSL=false. If you dont want your own reverse Proxy set SSL=true and place the certificates in the folder /etc/certs/cert.pem and /etc/certs/cert.key. For the deamon containers you can configure this easily in the webinterface. I have for each deamon a own subdomain.

**Comment by Syntax3rror404** [comment]
I think this issue can be closed.
