### ISSUE TITLE
Unraid + Pterodactyl-docker

### ISSUE THREAD

**Issue by Brzam** [ccarney16/pterodactyl-docker#48]
Hey been trying to get this Docker working on Unraid however had been running into issues, I've assigned all the ports and folders appropriately but end up with the [Warning] Disabling HTTPS error on startup.

Any chance of this getting added to the CA on Unraid? Would be extremely helpful, or atleast some guidance of how to progress past this error within the Unraid Ecosystem :)

**Comment by Syntax3rror404** [comment]
I think you can use your own reverse proxy to avoid this error. Does this failure appear during the container start?

**Comment by ccarney16** [comment]
That is a warning, not an error. It is set as an option to allow users to enable or disable HTTPS for the panel (Just in case someone cant use https on the backend). 
Here is the environment to enable SSL:
```
SSL=true
SSL_CERT="/etc/certs/cert.pem"
SSL_CERT_KEY="/etc/certs/cert.key"
```

This image is expected to work on most standard docker platforms (Ubuntu, CentOS). I have not worked with unraid, and I do not plan on using it in the near future. However, I will be redoing documentation (and actually use github's wiki) when the next major release of pterodactyl comes out. Hopefully that will assist with anyone that do not use docker-compose to manage their containers.
