### ISSUE TITLE
Daemon is remembering deleted containers

### ISSUE THREAD

**Issue by kazasho** [ccarney16/pterodactyl-docker#49]
Hello,

due to some testing on creating a custom egg... some were a complete miss of course... and after these misses, the daemon keeps remembering the deleted containers. I used the safe deletion option, when I tried to delete the borked servers.

Every time i start the daemon now, it outputs this:

05:03:06.948Z  WARN wings: Could not locate a server data directory. Skipping initialization of server. (server=5c979546-3069-495d-87e5-3fcb1f2db37c, err.code=ENOENT)
    Error: ENOENT: no such file or directory, stat '/srv/daemon-data/5c979546-3069-495d-87e5-3fcb1f2db37c'
05:03:06.949Z  WARN wings: Could not locate a server data directory. Skipping initialization of server. (server=5e36c854-fb32-4cd1-928f-99fd65bf7ebf, err.code=ENOENT)
    Error: ENOENT: no such file or directory, stat '/srv/daemon-data/5e36c854-fb32-4cd1-928f-99fd65bf7ebf'
05:03:06.949Z  WARN wings: Could not locate a server data directory. Skipping initialization of server. (server=a008ca75-a4e2-40ff-aa5e-08b435fc9e8a, err.code=ENOENT)
    Error: ENOENT: no such file or directory, stat '/srv/daemon-data/a008ca75-a4e2-40ff-aa5e-08b435fc9e8a'
05:03:06.951Z  WARN wings: Could not locate a server data directory. Skipping initialization of server. (server=fcfc81ba-f9ba-4d51-a2d3-c80b15ee86ce, err.code=ENOENT)
    Error: ENOENT: no such file or directory, stat '/srv/daemon-data/fcfc81ba-f9ba-4d51-a2d3-c80b15ee86ce'

It's not breaking anything... but I like to clean up, after my mess.

When posting in the official pterodactyl support Discord, their bot suggested the following:

"It looks like your server may have failed to install or was deleted and the config was never cleaned up."

How does one clean up this?

I have ran docker-compose down --volumes , and then docker-compose up -d daemon... But it still remembers it

**Comment by ccarney16** [comment]
That is rather odd, did you not force delete servers? Did you modify the volume info for the daemon?

**Comment by kazasho** [comment]
No, I only use the safe deletion option... To avoid issues like this x)

Since I docker-compose -down --volumes.. I guess it's stuck somewhere in the SQL database? I run MySQL on a different server, so it's not affected by me taking down the volumes. But where would it be in there?

**Comment by ccarney16** [comment]
MySQL is unrelated to this. However, mind if I can get logs for the daemon upon server deletion?

**Comment by kazasho** [comment]
Is there a way for me to find logs from earlier daemon containers? I can find the current with docker logs pterodactyl_daemon_1... but that doesen't help much.

I can't recreate the issue, since this happened while I made a custom egg, that is now working.. (dammit, should have saved a copy of the broken files...)

**Comment by ccarney16** [comment]
you can always use `docker-compose logs daemon` to view general logs. otherwise, you do need to exec into the container in `/srv/daemon/logs`.

**Comment by kazasho** [comment]
Yeah, the earliest logs are from today... And this problem happened yesterday... So that's giving me no clues... Should probably be more careful with the down --volumes action...

Do we have any clue to where wings reads it's launch settings from? Then I could look there for some more clues

**Comment by ccarney16** [comment]
Are you using mounts or volumes under docker-compose?

**Comment by kazasho** [comment]
Actually... your right... I don't use any volumes to store persistent data... I have just gotten used to it, trough other docker apps.

So then, since one has to shutdown the daemon, for egg changes to take effect... I should not down the container, but instead stop the service inside of the daemon container? Or one could setup a persistent log directory...

Anyhow... I can not recreate this issue, since the egg I was creating, that lead to these strange bugs... are fixed. I guess we can close this issue with that... and I gotta try to clean it out from my installation... somehow.

Thanks for your assistance
