### ISSUE TITLE
PHP Fatal error:  Uncaught ReflectionException: Class db.connection does not exist

### ISSUE THREAD

**Issue by TECHNOFAB11** [ccarney16/pterodactyl-docker#56]
Log: https://pastebin.com/cvFaP9r6
Config: https://pastebin.com/vkmZCfMM
Screenshot of Portainer: https://pasteboard.co/J6Ybl0Q.png

Tried recreating the server multiple times, but nothing made it work.

**Comment by ccarney16** [comment]
Did you run the container before hand to generate all the configurations and db connections?

**Comment by TECHNOFAB11** [comment]
I ran the container not the docker-compose if you mean that, yes. I already have a MySQL server, so i wanted to use that. I dont have a Redis server running, but as the issue seems to be with MySQL i guess thats not a problem right now? Like said, simply pulled from Portainer and deployed, then changed the config, restartet (and re-deployed/recreated, but didnt matter) but i get the same error

**Comment by ccarney16** [comment]
I suggest looking through docker-compose and .env for all information. I really suggest getting redis up and running as that could be another issue. Id also check the database to see if the tables have been created and seeded.

**Comment by TECHNOFAB11** [comment]
Checked the DB but there are no Tables. Will create a Redis instance but I don't think that that will make it work. Like said, I didn't use docker-compose as i have MySQL running already, so I just pulled the image itself. Will try with docker-compose / modify it to check if it works then

**Comment by ccarney16** [comment]
The panel needs to know where the database is, either within `/data/pterodactyl.conf` or within your environment. you can get the variables within `.env.example`:

```
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=pterodactyl
DB_USERNAME=ptero
DB_PASSWORD=pterodbpass
```

**Comment by TECHNOFAB11** [comment]
Yeah, thats how i configured it: https://pastebin.com/iW1GbTqp

**Comment by ccarney16** [comment]
your logs have expired from may, but if the container does not create your database tables, you need to create them manually by running `docker-compose run --rm panel php artisan migrate --seed` or by creating a non permanent container.

**Comment by TECHNOFAB11** [comment]
Thanks, after doing it with Docker compose and running the migrate command it worked! I can at least access it and login, but will test it out more
