### ISSUE TITLE
cant import an egg

### ISSUE THREAD

**Issue by elRazer** [ccarney16/pterodactyl-docker#6]
the installation runs perfectly but if I want to add an egg, the following appears
"Whoops, looks like something went wrong."
chrome console says
"Failed to load resource: the server responded with a status of 500"
the panel log says "production.ERROR: LogicException: Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?) in /var/www/html/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php:130"

btw
im running the docker behind a nginx proxy

**Comment by MrFlutters** [comment]
This docker image does not seem to be able to import egg's successfully without php7-fileinfo.
Adding this to my own image fixes the issue
```Dockerfile
FROM ccarney16/pterodactyl-panel:v0.7.11
RUN apk --update add php7-fileinfo
```

However, I was not able to simply edit the manifests/panel/dockerfile as tini gives permission denied after rebuilding.

https://github.com/ccarney16/pterodactyl-docker/blob/4d8ce63085aa5853605aa6c17b80c8a14f95570d/manifest/panel/Dockerfile#L10-L14
___
I am also running both the panel and daemon behind a [traefik](https://traefik.io/) proxy

**Comment by Sporesirius** [comment]
Are you using another init packet ?

**Comment by MrFlutters** [comment]
no, simply adding the package fixes the image for me, without changing anything else

**Comment by Sporesirius** [comment]
Where did you add it?
I mean adding the fix in to the Dockerfile doesn't work for me.
`FROM ccarney16/pterodactyl-panel:v0.7.11
RUN apk --update add php7-fileinfo`

**Comment by MrFlutters** [comment]
I made another dockerfile with the two lines above and built another image ontop of it, 
example below.

`docker build -t mrflutters/pterodactyl-panel:v0.7.11-hotfix -f Dockerfile-fix . `

(-f is what you named your dockerfile) 
(the dot is needed, make sure you are in the directory with the new dockerfile)

then replace the panel image with the built image, in the above example the image is 

`mrflutters/pterodactyl-panel:v0.7.11-hotfix`

**Comment by Sporesirius** [comment]
Do i need to upload the image? for example myname/pterodactyl-panel:v0.7.11-hotfix doesn't work?
what did i do wrong :D

**Comment by MrFlutters** [comment]
what doesn't work, the build or the image?

**Comment by MrFlutters** [comment]
I just forked and built an image with the fix you can use [here](https://hub.docker.com/r/mrflutters/pterodactyl-panel)

or you can look at my git fork [here ](https://github.com/MrFlutters/pterodactyl-docker) to see how i did it.

[commit](https://github.com/MrFlutters/pterodactyl-docker/commit/301eec840aacf85efc32d053e9b386af5829ef76)
___
![img1](https://img.fluttershub.com/2mSBHJu5XVEY.png)
![img2](https://img.fluttershub.com/pB2VtOsX02cM.png)

**Comment by Sporesirius** [comment]
Thanks and sorry for my incompetence in docker matters. 😄

**Comment by MrFlutters** [comment]
@elRazer you should keep the issue open until it is updated on the main image or @ccarney16 addresses it,

**Comment by elRazer** [comment]
ah yes right

**Comment by ccarney16** [comment]
This should be fixed now, I just added in the dependency into the now updated containers. Thank you @elRazer for bringing it up and @MrFlutters for addressing it. I will keep this open for now if any more problems pop up for this issue.

**Comment by MrFlutters** [comment]
Image seems to be working now on my end.
