### ISSUE TITLE
Daemon and panel struggle to detect latest versions.

### ISSUE THREAD

**Issue by MrFlutters** [ccarney16/pterodactyl-docker#8]
Panel currently reports 0.7.11 as latest when 0.7.12 is out

Aswell as the daemon reports error as latest available version

____
## Panel 
![](https://img.fluttershub.com/JC2Jb8P5atYq.png)

## Daemon
![](https://img.fluttershub.com/ZiXxv5nLM7ZK.png)

**Comment by ccarney16** [comment]
Odd, I have not updated the panel due in part of the developers pushing 5-6 updates within a given timeframe. However I have not modified this function and works fine on my installations.

**Comment by MrFlutters** [comment]
I havent been able to pin down whats causing this, it seems to get version info using php, however the panel and daemon itself can see and receive data from the url, and nothing spits out any errors.

However it does not seem like a priority as everything works as intented.

So it does not seem to be an issue with your implantation and I'll reply to this if i ever get time to pin down the exact cause.
